#!/usr/bin/with-contenv bash
# Generates the Alloy config from environment variables and writes it to stdout.
# Inputs (env): LOG_LEVEL, JOURNAL_PATH, LOKI_URL, PROMETHEUS_URL, PROMETHEUS_USERNAME,
#   INSTANCE_NAME, METRICS_SCRAPE_INTERVAL, ADDITIONAL_CONFIG.
# The Prometheus password is NOT interpolated here; the config references
# sys.env("PROMETHEUS_PASSWORD") so the secret never lands on disk.
set -eu

LOG_LEVEL="${LOG_LEVEL:-info}"
JOURNAL_PATH="${JOURNAL_PATH:-/var/log/journal}"
LOKI_URL="${LOKI_URL:-}"
PROMETHEUS_URL="${PROMETHEUS_URL:-}"
PROMETHEUS_USERNAME="${PROMETHEUS_USERNAME:-}"
INSTANCE_NAME="${INSTANCE_NAME:-homeassistant}"
METRICS_SCRAPE_INTERVAL="${METRICS_SCRAPE_INTERVAL:-60s}"
ADDITIONAL_CONFIG="${ADDITIONAL_CONFIG:-}"

cat <<ALLOYCONFIG
// Grafana Alloy config - auto-generated by HAOS add-on
// Do not edit directly - configure via add-on options

logging {
  level = "${LOG_LEVEL}"
}
ALLOYCONFIG

if [ -n "${LOKI_URL}" ]; then
cat <<ALLOYCONFIG

// --- Read systemd journal ---
loki.source.journal "journal" {
  path         = "${JOURNAL_PATH}"
  forward_to   = [loki.process.journal.receiver]
  relabel_rules = loki.relabel.journal.rules
  labels       = {
    job = "systemd-journal",
  }
}

// --- Relabel journal fields ---
loki.relabel "journal" {
  forward_to = []

  rule {
    source_labels = ["__journal__systemd_unit"]
    target_label  = "unit"
  }
  rule {
    source_labels = ["__journal__hostname"]
    target_label  = "hostname"
  }
  rule {
    source_labels = ["__journal_syslog_identifier"]
    target_label  = "syslog_identifier"
  }
  rule {
    source_labels = ["__journal__transport"]
    target_label  = "transport"
  }
  rule {
    source_labels = ["__journal_container_name"]
    target_label  = "container_name"
  }
}

// --- Process journal logs ---
loki.process "journal" {
  stage.drop {
    expression = "^\\\\s*\$"
  }

  // Extract log level from Home Assistant log format:
  // "2026-03-18 19:02:30.204 INFO (MainThread) [component] message"
  stage.regex {
    expression = "[0-9]{2}:[0-9]{2}:[0-9]{2}[.0-9]* (?P<extracted_level>DEBUG|INFO|NOTICE|WARNING|WARN|ERROR|CRITICAL|FATAL) "
  }

  stage.labels {
    values = {
      level = "extracted_level",
    }
  }

  forward_to = [loki.write.loki.receiver]
}

// --- Write to Loki ---
loki.write "loki" {
  endpoint {
    url = "${LOKI_URL}"
  }
}
ALLOYCONFIG
fi

if [ -n "${ADDITIONAL_CONFIG}" ] && [ "${ADDITIONAL_CONFIG}" != "null" ]; then
  printf '\n// --- Additional user config ---\n%s\n' "${ADDITIONAL_CONFIG}"
fi
